<?php

/**
 * BaseShopItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $title
 * @property string $description
 * @property string $images
 * @property decimal $price
 * @property string $email
 * @property boolean $is_active
 * @property timestamp $expires_at
 * @property ShopCategory $ShopCategory
 * 
 * @method integer      getCategoryId()   Returns the current record's "category_id" value
 * @method string       getTitle()        Returns the current record's "title" value
 * @method string       getDescription()  Returns the current record's "description" value
 * @method string       getImages()       Returns the current record's "images" value
 * @method decimal      getPrice()        Returns the current record's "price" value
 * @method string       getEmail()        Returns the current record's "email" value
 * @method boolean      getIsActive()     Returns the current record's "is_active" value
 * @method timestamp    getExpiresAt()    Returns the current record's "expires_at" value
 * @method ShopCategory getShopCategory() Returns the current record's "ShopCategory" value
 * @method ShopItem     setCategoryId()   Sets the current record's "category_id" value
 * @method ShopItem     setTitle()        Sets the current record's "title" value
 * @method ShopItem     setDescription()  Sets the current record's "description" value
 * @method ShopItem     setImages()       Sets the current record's "images" value
 * @method ShopItem     setPrice()        Sets the current record's "price" value
 * @method ShopItem     setEmail()        Sets the current record's "email" value
 * @method ShopItem     setIsActive()     Sets the current record's "is_active" value
 * @method ShopItem     setExpiresAt()    Sets the current record's "expires_at" value
 * @method ShopItem     setShopCategory() Sets the current record's "ShopCategory" value
 * 
 * @package    shops
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_item');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('images', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}