<?php

/**
 * BaseShopOrdered
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $item_id
 * @property string $email
 * @property string $status
 * 
 * @method integer     getItemId()  Returns the current record's "item_id" value
 * @method string      getEmail()   Returns the current record's "email" value
 * @method string      getStatus()  Returns the current record's "status" value
 * @method ShopOrdered setItemId()  Sets the current record's "item_id" value
 * @method ShopOrdered setEmail()   Sets the current record's "email" value
 * @method ShopOrdered setStatus()  Sets the current record's "status" value
 * 
 * @package    shops
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopOrdered extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_ordered');
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}