<?php

/**
 * BaseShopCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ShopItems
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getShopItems() Returns the current record's "ShopItems" collection
 * @method ShopCategory        setName()      Sets the current record's "name" value
 * @method ShopCategory        setShopItems() Sets the current record's "ShopItems" collection
 * 
 * @package    shops
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShopItem as ShopItems', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}