<?php

/**
 * ShopOrderedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopOrderedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ShopOrderedTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopOrdered');
    }
}