<?php

/**
 * ShopCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ShopCategoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopCategory');
    }
    public function getCategories()
    {
    	$q=$this->createQuery('c');
    	return $q->execute();
    }
}