<?php

/**
 * ShopItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ShopItemTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopItem');
    }
    public function getActiveItem(Doctrine_Query $q=null)
    {    	
    	return $this->getQuery($q)->execute();
    }
    public function retrieveActiveItem(Doctrine_Query $q)
    {
    	$q->andWhere('a.expires_at > ?', date('Y-m-d h:i:s', time()));
    	return $q->fetchOne();
    }

    public function getQuery(Doctrine_Query $q=null)
    {
        if (is_null($q))
        {
            $q=Doctrine_Query::create()
             ->from('ShopItem s');
        }
        $alias=$q->getRootAlias();
        $q->andWhere($alias . '.expires_at > ?', date('Y-m-d h:i:s', time()))
            ->addOrderBy($alias . '.expires_at DESC');
        return $q;
    }
}