ShopCategory:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }

ShopItem:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    title: { type: string(255), notnull: true }
    description: { type: string(4000), notnull: true }
    images: { type: string(255) }
    price: { type: decimal }
    email: { type: string(255) }
    is_active: { type: boolean, notnull: true, default: 0 }
    expires_at: { type: timestamp, notnull: true }
  relations:
    ShopCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: ShopItems }

ShopOrdered:
  actAs: { Timestampable: ~ }
  columns:
    item_id: { type: integer, notnull: true }
    email: { type: string(255) }
    status: { type: string(255) }